default:
    @just --list

status:
    @echo "Public self-study handout is already unpacked in ./handout."

run:
    test -x handout/bomb
    cd handout && ./bomb

gdb:
    test -x handout/bomb
    cd handout && gdb ./bomb

disasm:
    test -x handout/bomb
    cd handout && objdump -d ./bomb > bomb.asm && sed -n '1,120p' bomb.asm
